language: python
matrix:
  include:
  - env: TARGET=python35
  - env: TARGET=python36
sudo: required
services:
- docker
before_install:
- true
install:
- docker build . -t ${TARGET} -f .travis/${TARGET}.docker
before_script:
- true
script:
- true
deploy:
  provider: pypi
  user: sperkins
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  password:
    secure: NDCxdT7lCsb9jvBGYiOrGVOMA/iros2b+CRqkEDsDBiZKTwcND6oRmKzjzsnObV+XlIWy4+Ugvg/HWE8MRzZ9yFjQWZUH4Rog+q7yPt3pqCPesbaWFdZNp7HV4vNFVdNuSr2fHGA44iyi702pZIm1R3umQ2gnpXUZRf4lKiMzEOKcmMjqxrCBTYR3gbmcRmjD+sqGJF5H1DLXiX+sZLbWZayMlBhRoOtZS10lWW0Cv8/zNVE25+dRcZeBULmkv+Qdj5rWmwqSivXf3R6eRbb8qbRCxImrUJMnfgVPHvzbBVV2HCuiTOfQ5qn4GY5ZapqTtfbEQEV9NMftr9ddNDNHgxsaMVf0US/bex7eAytdfYT8XHO8Kzgah4/xii72M+XLlAFows/gRFvltrJfiG1wJJKEyOavBqBIlLxlvy94I4ESCYJ4gidRaN4r4aEduuGZ3m1dKUvpU6Ukj2jYmG297oIFaPZm/Ss7dUDH+YCzTFcSGwf+ZMTNcWb3W94IghA8pJGkIxU1yf8rsUXgZ+EyueWZ/7njnBFh378EqHctes4pxxNRSZM6F6HEY6ZIsTYWcsQL+P2mNhadTz4Ar8NGENg9/hMLdQRYdsxL/6BPSUhfw0OGGzgH3k+W5C4/V4AEAtdeqpUWNJixolXusV3+XCsf9CBxxgS6k8NWLTddkI=
  on:
    tags: true
    branch: master
    repo: ska-sa/tricolour
    python: 3.6
