 sum_threshold:
    outlier_nsigma: 4.5
    windows_time: [1, 2, 4, 8]
    windows_freq: [1, 2, 4, 8]
    background_reject: 2.0
    background_iterations: 1
    spike_width_time: 12.5
    spike_width_freq: 10.0
    time_extend: 3
    freq_extend: 3
    freq_chunks: 10
    average_freq: 1
    flag_all_time_frac: 0.6
    flag_all_freq_frac: 0.8
    rho: 1.3
