# only enable me if you really want to start from scratch
##reset_flags:
##    task: unflag
##    order: -1
nan_dropouts_flag:
    task: flag_nans_zeros
    order: 0
background_static_mask:
    task: apply_static_mask
    order: 1
    accumulation_mode: "or"
    uvrange: ""
background_flags:
    task: sum_threshold 
    order: 2
    outlier_nsigma: 5
    windows_time: [1, 2, 4, 8]
    windows_freq: [1, 2, 4, 8]
    background_reject: 2.0
    background_iterations: 5
    spike_width_time: 12.5
    spike_width_freq: 10.0
    time_extend: 3
    freq_extend: 3
    freq_chunks: 10
    average_freq: 1
    flag_all_time_frac: 0.6
    flag_all_freq_frac: 0.8
    rho: 1.3
    num_major_iterations: 5
residual_flag_initial:
    task: uvcontsub_flagger
    order: 3
    major_cycles: 7
    or_original_from_cycle: 1
    taylor_degrees: 10
    sigma: 7.0
# flags are discarded at this point since we or from cycle 1
# reflag nans and zeros
nan_dropouts_reflag:
    task: flag_nans_zeros
    order: 4
uvrange_static_mask:
    task: apply_static_mask
    order: 5
    accumulation_mode: "or"
    uvrange: "0~400"
final_st_very_broad:
    task: sum_threshold 
    order: 6
    outlier_nsigma: 10
    windows_time: [1, 2, 4, 8]
    windows_freq: [32, 48, 64, 128]
    background_reject: 2.0
    background_iterations: 5
    spike_width_time: 6.5
    spike_width_freq: 64.0
    time_extend: 3
    freq_extend: 3
    freq_chunks: 10
    average_freq: 1
    flag_all_time_frac: 0.6
    flag_all_freq_frac: 0.8
    rho: 1.3
    num_major_iterations: 2
final_st_broad:
    task: sum_threshold 
    order: 7
    outlier_nsigma: 5
    windows_time: [1, 2, 4, 8]
    windows_freq: [1, 2, 4, 8]
    background_reject: 2.0
    background_iterations: 5
    spike_width_time: 6.5
    spike_width_freq: 10.0
    time_extend: 3
    freq_extend: 3
    freq_chunks: 10
    average_freq: 1
    flag_all_time_frac: 0.6
    flag_all_freq_frac: 0.8
    rho: 1.3
    num_major_iterations: 2
final_st_narrow:
    task: sum_threshold 
    order: 8
    outlier_nsigma: 8
    windows_time: [1, 2, 4, 8]
    windows_freq: [1, 2, 4, 8]
    background_reject: 2.0
    background_iterations: 5
    spike_width_time: 2
    spike_width_freq: 10.0
    time_extend: 3
    freq_extend: 3
    freq_chunks: 10
    average_freq: 1
    flag_all_time_frac: 0.6
    flag_all_freq_frac: 0.8
    rho: 1.3
    num_major_iterations: 2
residual_flag_final:
    task: uvcontsub_flagger
    order: 9
    major_cycles: 7
    or_original_from_cycle: 0
    taylor_degrees: 15
    sigma: 7.0
flag_autos:
    task: flag_autos
    order: 10
combine_with_input_flags:
    task: combine_with_input_flags
    order: 11
