reset_flags:
    task: unflag
    order: 0
background_static_mask:
    task: apply_static_mask
    order: 1
    accumulation_mode: "or"
    uvrange: ""
background_flags:
    task: sum_threshold 
    order: 2
    outlier_nsigma: 5
    windows_time: [1, 2, 4, 8]
    windows_freq: [1, 2, 4, 8]
    background_reject: 2.0
    background_iterations: 1
    spike_width_time: 12.5
    spike_width_freq: 10.0
    time_extend: 3
    freq_extend: 3
    freq_chunks: 10
    average_freq: 1
    flag_all_time_frac: 0.6
    flag_all_freq_frac: 0.8
    rho: 1.3
    num_major_iterations: 5
residual_flag:
    task: uvcontsub_flagger
    order: 3
    major_cycles: 5
    or_original_from_cycle: 1
    taylor_degrees: 10
    sigma: 3.0
short_spacings_static_mask:
    task: apply_static_mask
    order: 4
    accumulation_mode: "or"
    uvrange: "0~650m"
final_sum_threshold_broad:
    task: sum_threshold 
    order: 5
    outlier_nsigma: 3.5
    windows_time: [1, 2, 4, 8]
    windows_freq: [1, 2, 4, 8]
    background_reject: 2.0
    background_iterations: 5
    spike_width_time: 10.0
    spike_width_freq: 6.0
    time_extend: 3
    freq_extend: 3
    freq_chunks: 10
    average_freq: 1
    flag_all_time_frac: 0.6
    flag_all_freq_frac: 0.8
    rho: 1.3
    num_major_iterations: 4
final_sum_threshold_narrow:
    task: sum_threshold 
    order: 6
    outlier_nsigma: 3.5
    windows_time: [1, 2, 4, 8]
    windows_freq: [1, 2, 4, 8]
    background_reject: 2.0
    background_iterations: 5
    spike_width_time: 10.0
    spike_width_freq: 2.0
    time_extend: 3
    freq_extend: 3
    freq_chunks: 10
    average_freq: 1
    flag_all_time_frac: 0.6
    flag_all_freq_frac: 0.8
    rho: 1.3
    num_major_iterations: 4
final_residual_flag:
    task: uvcontsub_flagger
    order: 6
    major_cycles: 5
    or_original_from_cycle: 1
    taylor_degrees: 10
    sigma: 3.0
flag_autos:
    task: flag_autos
    order: 7
combine_with_input_flags:
    task: combine_with_input_flags
    order: 8
